################################################################################
#                               Project Manifest                               #
#                                                                              #
# This file describes the `bitvec` Rust project to the Rust build tool, Cargo. #
################################################################################

[package]
name = "bitvec"
version = "0.17.2"
authors = [
	"myrrlyn <self@myrrlyn.dev>",
]
categories = [
	"data-structures",
	"embedded",
	"no-std",
	"rust-patterns",
]
description = "A crate for manipulating memory, bit by bit"
documentation = "https://docs.rs/bitvec"
edition = "2018"
homepage = "https://myrrlyn.net/crates/bitvec"
include = [
	"Cargo.toml",
	"src/**/*.rs",
]
keywords = [
	"bitfields",
	"bits",
	"bitstream",
	"bitvec",
	"bitvector",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/myrrlyn/bitvec"
exclude = [ "/sgx/*", ]

[features]
alloc = []
atomic = []
default = [
	"atomic",
	"std",
    "mesalock_sgx",
]
std = [
	"alloc",
    "mesalock_sgx",
]
mesalock_sgx = [
    "std",
    "sgx_tstd",
]

[dependencies]
funty = "1"
radium = "0.3"
sgx_tstd = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dependencies.serde]
#default-features = false
git = "https://github.com/mesalock-linux/serde-sgx"
features = [
	"derive",
]
optional = true
version = "1"

# Crates required when running the test suite.
[dev-dependencies]
#serde = "1"
#serde_json = "1"
#serde_test = "1"

# Indicates the features that docs.rs should enable when building documentation.
[package.metadata.docs.rs]
features = [
	"atomic",
	"serde",
	"std",
]

[badges.codecov]
repository = "myrrlyn/bitvec"
branch = "master"
service = "github"

[badges.is-it-maintained-issue-resolution]
repository = "myrrlyn/bitvec"

[badges.is-it-maintained-open-issues]
repository = "myrrlyn/bitvec"

[badges.maintenance]
status = "actively-developed"
